# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yudhir Khanal
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yudhir.com.np" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: y2kyudhir
github_username:  yudhir

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.17.2"
minimal_mistakes_skin: neon

paginate: 5


plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
defaults:
  # _docs
  - scope:
      path: ""
      type: blog
    values:
      sidebar:
        nav: "sidebarnav"

author:
  name   : "Yudhir Khanal"
  avatar : "/assets/images/YudhirSketch 2-02.png"
  bio    : "Hello Dev"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://yudhir.com.np"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/y2kyudhir"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yudhir"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/zuck"
    - label: "Paypal"
      icon: "fab fa-fw fa-paypal"
      url: "https://www.paypal.com/donate/?hosted_button_id=PYSFRZU6UC892"
        
  
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/y2kyudhir"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yudhir"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/zuck"
    - label: "Paypal"
      icon: "fab fa-fw fa-paypal"
      url: "https://www.paypal.com/donate/?hosted_button_id=PYSFRZU6UC892"
